blog/urls.py
from django.urls import path

from blog import views
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('create/', views.PostCreateView.as_view(), name='post_create'),
    path('<slug:slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('<slug:slug>/update/', views.PostUpdateView.as_view(), name='post_update'),
    path('<slug:slug>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
]

client/urls.py
from django.urls import path

from client import apps, views

app_name = apps.ClientConfig.name

urlpatterns = [
    path('client/list', views.ClientListView.as_view(), name='client_list'),
    path('client/create', views.ClientCreateView.as_view(), name='client_create'),
    path('client/<int:pk>', views.ClientDetailView.as_view(), name='client_detail'),
    path('client/<int:pk>/update', views.ClientUpdateView.as_view(), name='client_update'),
    path('client/<int:pk>/delete', views.ClientDeleteView.as_view(), name='client_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls', namespace='user'), name='user'),
    path('blog/', include('blog.urls', namespace='blog'), name='blog'),
    path('mailer/', include('mailer.urls', namespace='mailer'), name='mailer'),
    path('', lambda request: redirect('mailer:home', permanent=True)),
    path('client/', include('client.urls', namespace='client'), name='client'),

    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

client/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

from utils.const import NULLABLE


class Client(models.Model):
    email = models.EmailField(max_length=100, verbose_name='Почтовый ящик')
    fullname = models.CharField(max_length=100, verbose_name='ФИО')
    comment = models.CharField(max_length=100, **NULLABLE, verbose_name='Заметка')
    owner = models.ForeignKey(
        to=get_user_model(),
        **NULLABLE,
        on_delete=models.SET_NULL,
        related_name='client',
        verbose_name='Владелец',
    )

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'
        ordering = ['id']
        permissions = [
            ('view_client_list', 'Может просматривать список клиентов')
        ]

    def __str__(self):
        return self.email

    def get_absolute_url(self):
        return reverse('client:client_detail', kwargs={'pk': self.pk})

client/forms.py
from django import forms

from client.models import Client


class ClientForm(forms.ModelForm):

    class Meta:
        model = Client
        fields = ['email', 'fullname', 'comment']
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'fullname': forms.TextInput(attrs={'class': 'form-control'}),
            'comment': forms.TextInput(attrs={'class': 'form-control'}),
            'owner': forms.Select(attrs={'class': 'form-control'}),
        }

client/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from client.forms import ClientForm
from client.models import Client
from mailer.utils import MenuMixin


class ClientListView(LoginRequiredMixin, MenuMixin, ListView):
    model = Client
    paginate_by = 3
    page_title = 'Список всех клиентов'
    page_description = 'Здесь отображены все клиенты добавленные вами'

    def get_queryset(self):
        return self.model.objects.filter(owner=self.request.user)


class ClientDetailView(LoginRequiredMixin, MenuMixin, DetailView):
    model = Client
    page_description = 'Здесь можно просмотреть информацию о клиенте'

    def get_context_data(self, **kwargs):
        return self.get_mixin_context(
            context=super().get_context_data(**kwargs),
            title=f'Страница просмотра клиента "{self.object.fullname}"',
        )

    def get_object(self, queryset=None):
        return get_object_or_404(self.model, pk=self.kwargs['pk'], owner=self.request.user)


class ClientCreateView(LoginRequiredMixin, MenuMixin, CreateView):
    model = Client
    form_class = ClientForm
    page_title = 'Страница создания клиента'
    page_description = 'Здесь можно создать нового клиента'

    def get_success_url(self):
        return reverse_lazy('client:client_detail', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, MenuMixin, UpdateView):
    model = Client
    form_class = ClientForm
    template_name = 'client/client_form.html'
    page_title = 'Страница редактирования клиента'
    page_description = 'Здесь можно редактировать информацию о клиенте'


class ClientDeleteView(LoginRequiredMixin, MenuMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('client:client_list')
    page_title = 'Страница удаления клиента'
    page_description = 'Здесь можно удалить клиента'

client/templates/client/client_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <div class="row row-cols-1 row-cols-md-2 g-4">
        <div class="col">
            <div class="card h-100">
                <div class="card-body">
                    <h3 class="card-title">Удаляемая запись: "{{ object }}"</h3>
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <a type="submit" class="btn btn-lg btn-block btn-outline-warning" href="javascript:history.go(-1)">Назад</a>
                        <input type="submit" class="btn btn-lg btn-block btn-outline-danger" value="Удалить">
                    </form>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

client/templates/client/client_detail.html
{% extends 'base.html' %}

{% block content %}

    <div class="mt-auto mb-3 mx-3">
        <a href="{% url 'client:client_list' %}" class="btn btn-lg btn-block btn-outline-warning">Все клиенты</a>
    </div>

    <div class="row row-cols-1 row-cols-md-1 g-4">
        <div class="col">
            <div class="card h-100">
                <div class="card-body">
                    <h3 class="card-title">{{ object.fullname }} - {{ object.email }}</h3>
                    <div class="card-body">
                        {{ object.comment }}
                    </div>
                    <a type="submit" class="btn btn-lg btn-block btn-outline-warning" href="javascript:history.go(-1)">Назад</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

client/templates/client/client_form.html
{% extends 'base.html' %}

{% block content %}
    <div class="row row-cols-1 row-cols-md-2 g-4">
        <div class="col">
            <div class="card h-100">
                <div class="card-body">
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row-form-errors">{{ form.non_field_errors }}</div>

                        {% for field in form %}
                            <p><label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field }}
                            </p>
                            <div class="form-error text-danger">
                                <p>{{ field.errors }}</p>
                            </div>
                        {% endfor %}

                        <a type="submit" class="btn btn-lg btn-block btn-outline-warning" href="javascript:history.go(-1)">Назад</a>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-warning" name="button_buy"
                                value="{{ product.pk }}">Сохранить
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

client/templates/client/client_list.html
{% extends 'base.html' %}

{% block content %}

    <div class="mt-auto mb-3 mx-3">
        <a href="{% url 'client:client_create' %}" class="btn btn-lg btn-block btn-outline-warning">
            Создать
        </a>
    </div>

    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Имя</th>
            <th scope="col">Почта</th>
            <th scope="col">Заметка</th>
            <th scope="col">Действия</th>
        </tr>
        </thead>
        <tbody>
        {% for client in object_list %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ client.fullname }}</td>
                <td>{{ client.email }}</td>
                <td>{{ client.comment|truncatechars:30 }}</td>

                <td>
                    <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                        <a href="{% url 'client:client_detail' client.pk %}" class="btn btn-outline-warning">
                            Смотреть
                        </a>
                        <a href="{% url 'client:client_update' client.pk %}" class="btn btn-outline-warning">
                            Изменить
                        </a>
                        <a href="{% url 'client:client_delete' client.pk %}" class="btn btn-outline-danger">
                            Удалить
                        </a>
                    </div>
                </td>

            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% btn_nav paginator page_obj %}

{% endblock %}