blog/urls.py
from django.urls import path

from blog import views
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('create/', views.PostCreateView.as_view(), name='post_create'),
    path('<slug:slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('<slug:slug>/update/', views.PostUpdateView.as_view(), name='post_update'),
    path('<slug:slug>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls', namespace='user'), name='user'),
    path('blog/', include('blog.urls', namespace='blog'), name='blog'),
    path('mailer/', include('mailer.urls', namespace='mailer'), name='mailer'),
    path('', lambda request: redirect('mailer:home', permanent=True)),
    path('client/', include('client.urls', namespace='client'), name='client'),

    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
import transliterate
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

from utils.const import NULLABLE


class PublishedManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().filter(is_published=True).order_by('-time_update')


class Post(models.Model):
    title = models.CharField(max_length=255, verbose_name='Заголовок')
    slug = models.SlugField(max_length=255, unique=True, **NULLABLE, verbose_name='URL')
    content = models.TextField(**NULLABLE, verbose_name='Содержание')
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    time_update = models.DateTimeField(auto_now=True, verbose_name='Время изменения')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    photo = models.ImageField(upload_to='photos/blog/%Y/%m/%d/', **NULLABLE, default=None, verbose_name='Фото')
    view_count = models.IntegerField(default=0, verbose_name='Количество просмотров')
    author = models.ForeignKey(
        to=get_user_model(),
        on_delete=models.SET_NULL,
        default=None,
        **NULLABLE,
        related_name='post',
        verbose_name='Автор'
    )

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ['time_create']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = transliterate.slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.slug})

blog/forms.py
from django import forms

from blog.models import Post


class PostForm(forms.ModelForm):
    ALLOWED_CHARS = set('АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЬЫЪЭЮЯабвгдеёжзийклмнопрстуфхцчшщьыъэюя- ')

    class Meta:
        model = Post
        fields = ['title', 'content', 'photo']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
            'photo': forms.FileInput(attrs={'class': 'form-control'}),
        }

    def clean_title(self):
        title = self.cleaned_data['title']
        if not all(char in self.ALLOWED_CHARS for char in title):
            raise forms.ValidationError('Должны быть только: русские символы, дефис или пробел')
        return title

blog/views.py
import transliterate
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.cache import cache
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from blog.forms import PostForm
from blog.models import Post
from blog.utils import send_mail_custom
from mailer.utils import MenuMixin, cache_for_queryset
from config import settings


class PostListView(MenuMixin, ListView):
    model = Post
    page_title = 'Список статей'
    page_description = 'Здесь можно посмотреть все статьи'
    paginate_by = 3

    def get_queryset(self):
        queryset = cache_for_queryset(
            key=settings.CACHE_POST_LIST,
            queryset=self.model.published.all().select_related('author')
        )
        return queryset


class PostDetailView(MenuMixin, DetailView):
    model = Post

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        obj.view_count += 1
        obj.save(update_fields=['view_count'])

        if obj.view_count == 100:
            send_mail_custom(self.request, obj)

        return obj


class PostCreateView(LoginRequiredMixin, MenuMixin, CreateView):
    form_class = PostForm
    model = Post
    template_name = 'blog/post_form.html'
    page_title = 'Страница для создания статьи'

    def get_success_url(self):
        cache.delete(settings.CACHE_POST_LIST)
        return reverse('blog:post_detail', kwargs={'slug': self.object.slug})

    def form_valid(self, form):
        slug = transliterate.slugify(form.cleaned_data['title'])
        if self.model.objects.filter(slug=slug).exists():
            form.add_error('title', 'Пост с таким slug уже существует')
            return self.form_invalid(form=form)

        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(UserPassesTestMixin, MenuMixin, UpdateView):
    form_class = PostForm
    model = Post
    template_name = 'blog/post_form.html'
    page_title = 'Страница для редактирования статьи'

    def get_success_url(self):
        cache.delete(settings.CACHE_POST_LIST)
        return reverse('blog:post_detail', kwargs={'slug': self.object.slug})

    def get_queryset(self):
        return Post.objects.filter(slug=self.kwargs['slug'])

    def test_func(self):
        check_perms = bool(
            self.get_object().author == self.request.user
            or self.request.user.is_superuser
            or self.request.user.has_perms(['blog.change_post'])
        )
        return check_perms


class PostDeleteView(UserPassesTestMixin, MenuMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:post_list')
    page_title = 'Страницы для удаление статьи'

    def get_success_url(self):
        cache.delete(settings.CACHE_POST_LIST)
        return reverse('blog:post_list')

    def test_func(self):
        check_perms = bool(
            self.get_object().author == self.request.user
            or self.request.user.is_superuser
            or self.request.user.has_perms(['blog.delete_post'])
        )
        return check_perms

blog/templates/blog/post_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <div class="row row-cols-1 row-cols-md-2 g-4">
        <div class="col">
            <div class="card h-100">
                <div class="card-body">
                    <h3 class="card-title">Удаляемая запись: "{{ object }}"</h3>
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <a type="submit" class="btn btn-lg btn-block btn-outline-warning" href="javascript:history.go(-1)">Назад</a>
                        <input type="submit" class="btn btn-lg btn-block btn-outline-danger" value="Удалить">
                    </form>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="row row-cols-1 row-cols-md-1 g-4">
        <div class="col">
            <div class="card h-100">
                <div class="card-body">
                    <h3 class="card-title">{{ post.title }}</h3>
                    <small class="text-body-secondary">Обновлено: {{ post.time_update|date:'d-m-Y H:i:s' }}</small><br>
                    <small class="text-body-secondary">Кол-во просмотров: {{ post.view_count }}</small><br>
                    <small class="text-body-secondary">Автор: {{ post.author }}</small><br>
                    <div class="card-body">
                        {{ post.content|linebreaks }}
                    </div>
                    <a type="submit" class="btn btn-lg btn-block btn-outline-warning" href="javascript:history.go(-1)">Назад</a>

                    {% if perms.blog.change_post or post.author == user %}
                    <a type="submit" class="btn btn-lg btn-block btn-outline-warning" href="{% url 'blog:post_update' post.slug %}">Редактировать</a>
                    {% endif %}
                    {% if perms.blog.delete_post or post.author == user %}
                    <a type="submit" class="btn btn-lg btn-block btn-outline-danger" href="{% url 'blog:post_delete' post.slug %}">Удалить</a>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/blog/post_form.html
{% extends 'base.html' %}

{% block content %}
    <div class="row row-cols-1 row-cols-md-2 g-4">
        <div class="col">
            <div class="card h-100">
                <div class="card-body">
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row-form-errors">{{ form.non_field_errors }}</div>

                        {% for field in form %}
                            <p><label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field }}
                            </p>
                            <div class="form-error text-danger">
                                <p>{{ field.errors }}</p>
                            </div>
                        {% endfor %}

                        <a type="submit" class="btn btn-lg btn-block btn-outline-warning" href="javascript:history.go(-1)">Назад</a>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-warning" name="button_buy"
                                value="{{ product.pk }}">Сохранить
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="row row-cols-1 row-cols-md-1 g-3">
        {% for post in object_list %}
            <div class="col">
                <div class="card h-100">
                    {% if post.photo and post.photo.path|file_exists %}
                        <img src="{{ post.photo.url }}" class="card-img-top object-fit-cover" height="180">
                    {% else %}
                        <svg class="bd-placeholder-img card-img-top" width="100%" height="180"
                             xmlns="http://www.w3.org/2000/svg" role="img"
                             aria-label="Placeholder: Заглушка изображения"
                             preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                            <rect width="100%" height="100%" fill="#868e96"></rect>
                            <text x="43%" y="50%" fill="#dee2e6" dy=".3em">Заглушка изображения</text>
                        </svg>
                    {% endif %}

                    <div class="card-body">
                        <h5 class="card-title">{{ post.title }}</h5>
                        <p class="card-text">
                            {{ post.content|truncatewords:50 }}
                        </p>
                    </div>
                    <div class="mt-auto mb-3 mx-3">
                        <a href="{{ post.get_absolute_url }}"
                           class="btn btn-lg btn-block btn-outline-warning" form="selected_post">Читать</a>
                    </div>
                    <div class="card-footer">
                        <small class="text-body-secondary">Обновлено: {{ post.time_update|date:'d-m-Y H:i:s' }}</small><br>
                        <small class="text-body-secondary">Кол-во просмотров: {{ post.view_count }}</small><br>
                        <small class="text-body-secondary">Автор: {{ post.author|get_name_or_email }}</small><br>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    {% btn_nav paginator page_obj %}

{% endblock %}