blog/urls.py
from django.urls import path

from blog import views
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('create/', views.PostCreateView.as_view(), name='post_create'),
    path('<slug:slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('<slug:slug>/update/', views.PostUpdateView.as_view(), name='post_update'),
    path('<slug:slug>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls', namespace='user'), name='user'),
    path('blog/', include('blog.urls', namespace='blog'), name='blog'),
    path('mailer/', include('mailer.urls', namespace='mailer'), name='mailer'),
    path('', lambda request: redirect('mailer:home', permanent=True)),
    path('client/', include('client.urls', namespace='client'), name='client'),

    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.views.generic import TemplateView

from users import views
from users.apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('register/', views.UserRegisterView.as_view(), name='register'),

    path('profile/', views.UserProfileView.as_view(), name='profile'),
    path('profile/update/', views.UserProfileUpdateView.as_view(), name='profile_update'),

    path('password-change/', views.UserPasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', views.UserPasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password-reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset/complete/', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('invalid_verify/', TemplateView.as_view(template_name='users/invalid_verify.html'),
         name='invalid_verify'),
    path('verify_email/<uidb64>/<token>/', views.EmailVerify.as_view(), name='verify_email'),
    path('confirm_email/', TemplateView.as_view(template_name='users/confirm_email.html'), name='confirm_email'),
    path('resend_email/', views.UserVerifyResendView.as_view(), name='resend_email'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.db import models
from django.utils.translation import gettext_lazy as _

from utils.const import NULLABLE


class User(AbstractUser):
    username_validator = UnicodeUsernameValidator()

    email = models.EmailField(max_length=50, unique=True, verbose_name='Электронная почта')
    email_verify = models.BooleanField(default=False)
    username = models.CharField(
        _("username"),
        max_length=150,
        unique=True,
        **NULLABLE,
        help_text=_(
            "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."
        ),
        validators=[username_validator],
        error_messages={
            "unique": _("A user with that username already exists."),
        },
    )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    class Meta(AbstractUser.Meta):
        permissions = [
            ('can_view_all_fields', 'Может просматривать всю админку'),
            ('can_view_is_staff', 'Может просматривать персонал'),
        ]

users/forms.py
from django import forms
from django.contrib.auth import get_user_model, authenticate
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm, PasswordResetForm, \
    SetPasswordForm
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


class WidgetsMixin:
    class Meta:
        widgets = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if hasattr(self.Meta, 'widgets'):
            widgets = self.Meta.widgets
            if widgets:
                for field_name, widget in widgets.items():
                    self.fields[field_name].widget = widget


class LabelsMixin:
    class Meta:
        labels = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if hasattr(self.Meta, 'labels'):
            labels = self.Meta.labels
            if labels:
                for field_name, label in labels.items():
                    self.fields[field_name].label = label


class UserLoginForm(WidgetsMixin, LabelsMixin, AuthenticationForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'password']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ваш логин'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Ваш пароль'}),
        }
        labels = {
            'username': 'Логин / E-mail',
        }

    def clean(self):
        email = self.cleaned_data.get('username')  # or self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        if email is not None and password is not None:
            self.user_cache = authenticate(self.request, email=email, password=password)

            if self.user_cache is None or not self.user_cache.email_verify:
                raise ValidationError('Электронная почта не подтверждена, проверьте свою электронную почту',
                                      code='invalid_login')

            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data


class UserRegisterForm(WidgetsMixin, UserCreationForm):
    email = forms.EmailField(
        label=_("Email"),
        max_length=254,
        widget=forms.EmailInput(attrs={'autocomplete': 'email'})
    )

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ['email', 'password1', 'password2']
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Ваш email'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Ваш пароль'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Повторите пароль'}),
        }


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ваш логин'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Ваш email'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ваше имя'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ваша фамилия'}),
        }
        labels = {
            'username': 'Логин',
        }


class UserProfileUpdateForm(LabelsMixin, WidgetsMixin, forms.ModelForm):
    email = forms.EmailField(disabled=True)

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ваш логин'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Ваш email'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ваше имя'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ваша фамилия'}),
        }
        labels = {
            'username': 'Логин',
        }


class UserPasswordChangeForm(WidgetsMixin, PasswordChangeForm):
    old_password = forms.CharField(label='Старый пароль')
    new_password1 = forms.CharField(label='Новый пароль')
    new_password2 = forms.CharField(label='Подтверждение пароля')

    class Meta:
        widgets = {
            'old_password': forms.PasswordInput(attrs={'class': 'form-control'}),
            'new_password1': forms.PasswordInput(attrs={'class': 'form-control'}),
            'new_password2': forms.PasswordInput(attrs={'class': 'form-control'}),
        }


class UserPasswordResetForm(WidgetsMixin, PasswordResetForm):
    class Meta:
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Ваш email'}),
        }


class UserSetPasswordForm(WidgetsMixin, SetPasswordForm):
    class Meta:
        widgets = {
            'new_password1': forms.PasswordInput(attrs={'class': 'form-control'}),
            'new_password2': forms.PasswordInput(attrs={'class': 'form-control'}),
        }

users/views.py
from django.contrib.auth import get_user_model, login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import default_token_generator as token_generator
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView, \
    PasswordResetView, PasswordResetConfirmView, PasswordResetCompleteView
from django.core.exceptions import ValidationError
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.http import urlsafe_base64_decode
from django.views import View
from django.views.generic import UpdateView, DetailView, FormView

from users.forms import UserLoginForm, UserRegisterForm, UserProfileUpdateForm, UserProfileForm, UserPasswordChangeForm, \
    UserPasswordResetForm, UserSetPasswordForm
from users.utils import send_email_for_verify


class UserLoginView(LoginView):
    template_name = 'users/login.html'
    form_class = UserLoginForm
    extra_context = {
        'title': 'Авторизация',
        'button': 'Войти',
    }


class UserLogoutView(LogoutView):
    pass


class UserRegisterView(FormView):
    form_class = UserRegisterForm
    model = get_user_model()
    template_name = 'users/user_form.html'
    success_url = reverse_lazy('user:confirm_email')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Регистрация'
        context['button'] = 'Зарегистрироваться'
        return context

    def form_valid(self, form):
        form.save()
        email = form.cleaned_data.get('email')
        password = form.cleaned_data.get('password1')
        user = authenticate(email=email, password=password)
        if not user.email_verify:
            send_email_for_verify(self.request, user)
        return super().form_valid(form)


class UserProfileView(LoginRequiredMixin, DetailView):
    form_class = UserProfileForm

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Мой профиль'

        attrs = [('username', 'Никнейм'), ('email', 'Почта'), ('first_name', 'Имя'),
                 ('last_name', 'Фамилия'), ('phone', 'Телефон'), ('country', 'Страна')]
        items = context['user']
        profile = {attrs[i][1]: getattr(items, attrs[i][0]) for i in range(len(attrs)) if hasattr(items, attrs[i][0])}
        context['profile'] = profile

        return context


class UserProfileUpdateView(LoginRequiredMixin, UpdateView):
    form_class = UserProfileUpdateForm
    extra_context = {
        'title': 'Редактирование профиля',
        'button': 'Сохранить',
    }

    def get_success_url(self):
        return reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserPasswordChangeView(PasswordChangeView):
    form_class = UserPasswordChangeForm
    template_name = 'users/password_change_form.html'
    success_url = reverse_lazy('users:password_change_done')
    extra_context = {
        'title': 'Смена пароля',
        'button': 'Сохранить',
    }


class UserPasswordChangeDoneView(PasswordChangeDoneView):
    template_name = 'users/password_change_done.html'
    extra_context = {
        'title': 'Ваш пароль был успешно изменен!',
        'button': 'Вернуться в профиль',
    }


class UserPasswordResetView(PasswordResetView):
    template_name = 'users/password_reset_form.html'
    email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    form_class = UserPasswordResetForm
    extra_context = {
        'title': 'Восстановление пароля',
        'button': 'Сбросить по E-mail',
    }


class UserPasswordResetDoneView(PasswordResetView):
    template_name = 'users/password_reset_done.html'
    extra_context = {
        'title': 'Сброс пароля',
    }


class UserPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'users/password_reset_confirm.html'
    success_url = reverse_lazy('users:password_reset_complete')
    form_class = UserSetPasswordForm
    extra_context = {
        'title': 'Новый пароль',
        'button': 'Сохранить',
    }


class UserPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'users/password_reset_complete.html'
    extra_context = {
        'title': 'Восстановление пароля завершено',
    }


class EmailVerify(View):
    template_name = 'users/verify_email.html'

    def get(self, request, uidb64, token):
        user = self.get_user(uidb64)

        if user is not None and token_generator.check_token(user, token):
            user.email_verify = True
            user.save()
            login(request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('mailer:home')
        elif request.user.is_authenticated:
            return redirect('mailer:home')

        return redirect('user:invalid_verify')

    @staticmethod
    def get_user(uidb64):
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = get_user_model().objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, get_user_model().DoesNotExist, ValidationError):
            user = None
        return user


class UserVerifyResendView(PasswordResetView):
    template_name = 'users/password_reset_form.html'
    email_template_name = 'users/verify_email.html'
    success_url = reverse_lazy('users:confirm_email')
    form_class = UserPasswordResetForm
    extra_context = {
        'title': 'Повторная отправка верефикации на E-mail',
        'button': 'Отправить',
    }

    def form_valid(self, form):
        email = form.cleaned_data.get('email')
        user = get_user_model().objects.filter(email=email, email_verify=False)
        if user.exists():
            return super().form_valid(form)
        return redirect('user:confirm_email')  # тут нужно подумать, в плане безопасности использования invalid_verify
        # или сделать огранниченое количество попыток на данных функционал

users/templates/users/confirm_email.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <p>Пожалуйста, проверьте свою почту, чтобы завершить регистрацию</p>
    </div>
{% endblock %}

users/templates/users/invalid_verify.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <p>Ваша ссылка некорректна, войдите снова</p>
        <a href="{% url 'user:login' %}">Войти</a>
    </div>
{% endblock %}

users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}

    <div class="row row-cols-1 row-cols-md-2 g-4">
        <div class="col">
            <div class="card h-100">
                <div class="card-header bg-dark-subtle">{{ title }}</div>
                <div class="card-body">
                    <form action="" method="post">

                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ next }}"/>
                        <div class="form-error text-danger">{{ form.non_field_errors }}</div>

                        {% for field in form %}
                            <p><label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field }}
                            </p>
                            <div class="form-error text-danger">
                                <p>{{ field.errors }}</p>
                            </div>
                        {% endfor %}

                        <p>
                            <button type="submit" class="btn btn-lg btn-block btn-outline-warning">
                                {{ button }}
                            </button>

                        {% if form.errors %}
                            <a class="small text-muted" href="{% url 'user:resend_email' %}">Выслать письмо еще раз?</a>
                        {% endif %}
                        </p>

                    </form>
                    <p>
                        <a type="submit" class="btn btn-lg btn-block btn-outline-warning"
                           href="{% url 'user:password_reset' %}">
                            Забыли пароль?
                        </a>
                        <a type="submit" class="btn btn-lg btn-block btn-outline-warning"
                           href="{% url 'user:register' %}">
                            Регистрация
                        </a>
                    </p>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/password_change_done.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <h1>{{ title }}</h1>

    <p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

    <p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

    <p>
        <a type="submit" class="btn btn-lg btn-block btn-outline-warning" href="{% url 'user:profile' %}">{{ button }}</a>
    </p>

{% endblock %}

users/templates/users/password_change_form.html
{% extends 'base.html' %}

{% block content %}

    <form action="" method="post">
        <div class="row row-cols-1 row-cols-md-2 g-4">
            <div class="col">
                <div class="card h-100">
                    <div class="card-header bg-dark-subtle">{{ title }}</div>
                    <div class="card-body">

                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ next }}"/>
                        <div class="form-error text-danger">{{ form.non_field_errors }}</div>

                        {% for field in form %}
                            <p><label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field }}
                            </p>
                            <div class="form-error text-danger">
                                <p>{{ field.errors }}</p>
                            </div>
                        {% endfor %}

                        <p>
                            <button type="submit" class="btn btn-lg btn-block btn-outline-warning">
                                {{ button }}
                            </button>
                        </p>

                    </div>
                </div>
            </div>
        </div>
    </form>

{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ title }}</h1>
    <p>Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для <a href="{% url 'users:login' %}"><strong>входа в систему</strong></a>.</p>

{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ title }}</h1>

    <form action="" method="post">
        {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>

        {% for f in form %}
            <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}

        <p>
            <button type="submit" class="btn btn-lg btn-block btn-outline-warning">
                {{ button }}
            </button>
        </p>
    </form>

{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <h1>{{ title }}</h1>

<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ title }}</h1>

    <form method="post">
        {% csrf_token %}

        {% for f in form %}
            <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}: </label>{{ f }}</p>
            <div class="form-error">{{ f.errors }}</div>
        {% endfor %}

        <p>
            <button type="submit" class="btn btn-lg btn-block btn-outline-warning">
                {{ button }}
            </button>
        </p>
    </form>

{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}

    <form action="" method="post">
        <div class="row row-cols-1 row-cols-md-2 g-4">
            <div class="col">
                <div class="card h-100">
                    <div class="card-header bg-dark-subtle">{{ title }}</div>
                    <div class="card-body">

                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ next }}"/>
                        <div class="form-error text-danger">{{ form.non_field_errors }}</div>

                        {% for field in form %}
                            <p><label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field }}
                            </p>
                            <div class="form-error text-danger">
                                <p>{{ field.errors }}</p>
                            </div>
                        {% endfor %}

                        <p>
                            <button type="submit" class="btn btn-lg btn-block btn-outline-warning">
                                {{ button }}
                            </button>
                        </p>

                    </div>
                </div>
            </div>
        </div>
    </form>

{% endblock %}

users/templates/users/user_detail.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}

    <div class="row row-cols-1 row-cols-md-2 g-4">
        <div class="col">
            <div class="card h-100">
                <div class="card-header bg-dark-subtle">{{ title }}</div>
                <div class="card-body">

                    {% if user.avatar and user.avatar.path|file_exists %}
                        <img src="{{ user.avatar.url }}" class="img-thumbnail rounded mx-auto d-block">
                    {% else %}
                        <svg class="img-thumbnail rounded mx-auto d-block" width="50%" height="180"
                             xmlns="http://www.w3.org/2000/svg" role="img"
                             aria-label="Placeholder: Заглушка изображения"
                             preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                            <rect width="100%" height="100%" fill="#868e96"></rect>
                            <text x="22%" y="50%" fill="#dee2e6" dy=".3em">Заглушка изображения</text>
                        </svg>
                    {% endif %}
                    <br><br>
                    <ul>
                        {% for k, v in profile.items %}
                            <li>
                                {{ k }}: {{ v|default:'Не указано' }}
                            </li>
                        {% endfor %}
                    </ul>

                </div>
                <div class="card-footer">
                    <a type="submit" class="btn btn-lg btn-block btn-outline-warning"
                       href="{% url 'user:profile_update' %}">
                        Редактировать
                    </a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'base.html' %}

{% block content %}

    <div class="row row-cols-1 row-cols-md-2 g-4">
        <div class="col">
            <div class="card h-100">
                <div class="card-header bg-dark-subtle">{{ title }}</div>
                <div class="card-body">
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ next }}"/>
                        <div class="form-error text-danger">{{ form.non_field_errors }}</div>

                        {% for field in form %}
                            <p><label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {{ field }}
                            </p>
                            <div class="form-error text-danger">
                                <p>{{ field.errors }}</p>
                            </div>
                        {% endfor %}

                        <p>
                            <button type="submit" class="btn btn-lg btn-block btn-outline-warning">
                                {{ button }}
                            </button>

                    </form>
                    {% if user.is_authenticated %}
                        <a type="submit" class="btn btn-lg btn-block btn-outline-warning"
                           href="{% url 'user:password_change' %}">Сменить пароль</a>
                    {% endif %}
                    </p>

                </div>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/verify_email.html
{% autoescape off %}

Привет, {{ user.get_username }}!
Пожалуйста, перейдите по ссылке, чтобы закончить регистрацию
{{ protocol }}://{{ domain }}{% url 'user:verify_email' uidb64=uid token=token %}

{% endautoescape %}