blog/urls.py
from django.urls import path

from blog import views
from blog.apps import BlogConfig

app_name = BlogConfig.name

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('create/', views.PostCreateView.as_view(), name='post_create'),
    path('<slug:slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('<slug:slug>/update/', views.PostUpdateView.as_view(), name='post_update'),
    path('<slug:slug>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
]

client/urls.py
from django.urls import path

from client import apps, views

app_name = apps.ClientConfig.name

urlpatterns = [
    path('client/list', views.ClientListView.as_view(), name='client_list'),
    path('client/create', views.ClientCreateView.as_view(), name='client_create'),
    path('client/<int:pk>', views.ClientDetailView.as_view(), name='client_detail'),
    path('client/<int:pk>/update', views.ClientUpdateView.as_view(), name='client_update'),
    path('client/<int:pk>/delete', views.ClientDeleteView.as_view(), name='client_delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('users.urls', namespace='user'), name='user'),
    path('blog/', include('blog.urls', namespace='blog'), name='blog'),
    path('mailer/', include('mailer.urls', namespace='mailer'), name='mailer'),
    path('', lambda request: redirect('mailer:home', permanent=True)),
    path('client/', include('client.urls', namespace='client'), name='client'),

    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailer/urls.py
from django.urls import path

from mailer import apps, views

app_name = apps.MailerConfig.name

urlpatterns = [
    path('', views.IndexTemplateView.as_view(), name='home'),

    path('message/list', views.MessageListView.as_view(), name='message_list'),
    path('message/create', views.MessageCreateView.as_view(), name='message_create'),
    path('message/<int:pk>', views.MessageDetailView.as_view(), name='message_detail'),
    path('message/<int:pk>/update', views.MessageUpdateView.as_view(), name='message_update'),
    path('message/<int:pk>/delete', views.MessageDeleteView.as_view(), name='message_delete'),

    path('settings/list', views.SettingsListView.as_view(), name='settings_list'),
    path('settings/create', views.SettingsCreateView.as_view(), name='settings_create'),
    path('settings/<int:pk>', views.SettingsDetailView.as_view(), name='settings_detail'),
    path('settings/<int:pk>/update', views.SettingsUpdateView.as_view(), name='settings_update'),
    path('settings/<int:pk>/delete', views.SettingsDeleteView.as_view(), name='settings_delete'),
]

users/urls.py
from django.urls import path
from django.views.generic import TemplateView

from users import views
from users.apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('register/', views.UserRegisterView.as_view(), name='register'),

    path('profile/', views.UserProfileView.as_view(), name='profile'),
    path('profile/update/', views.UserProfileUpdateView.as_view(), name='profile_update'),

    path('password-change/', views.UserPasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', views.UserPasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password-reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset/complete/', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('invalid_verify/', TemplateView.as_view(template_name='users/invalid_verify.html'),
         name='invalid_verify'),
    path('verify_email/<uidb64>/<token>/', views.EmailVerify.as_view(), name='verify_email'),
    path('confirm_email/', TemplateView.as_view(template_name='users/confirm_email.html'), name='confirm_email'),
    path('resend_email/', views.UserVerifyResendView.as_view(), name='resend_email'),
]

templates/base.html
{% load static %}
{% load custom_tags %}

<!doctype html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>

<nav class="navbar navbar-expand-lg bg-dark border-bottom border-body sticky-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">MailService</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% with url_name=request.resolver_match.url_name %}

                    {% for m in menu %}
                        <li class="nav-item" style="margin: 2px">
                            {% if m.submenu %}
                                <div class="dropdown">
                                    <a class="p-2 btn btn-outline-warning dropdown-toggle {% if m.active %}active{% endif %}"
                                       role="button"
                                       id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                                        {{ m.title }}
                                    </a>
                                    <ul class="dropdown-menu">
                                        {% for s in m.submenu %}
                                            <li>
                                                <a class="dropdown-item {% if s.active %}text-warning{% endif %}"
                                                   href="{% url s.url_name %}">{{ s.title }}</a>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            {% else %}
                                <a class="p-2 btn btn-outline-warning {% if request.resolver_match.view_name == m.url_name %}active{% endif %}"
                                   href="{% if m.url_name %}{% url m.url_name %}{% else %}#{% endif %}">
                                    {{ m.title }}
                                </a>
                            {% endif %}
                        </li>
                    {% endfor %}
                {% endwith %}
            </ul>

            <ul class="navbar-nav mb-2 mb-lg-0" style="margin: 2px">
                <li class="nav-item last">
                    {% if user.is_authenticated %}
                        <a class="p-2 btn btn-outline-warning" href="{% url 'user:profile' %}">
                            {{ user|get_name_or_email|truncatechars:20 }}
                        </a>
                        <a class="p-2 btn btn-outline-warning" href="{% url 'user:logout' %}">Выйти</a>

                    {% else %}
                        <a class="p-2 btn btn-outline-warning" href="{% url 'user:login' %}">Войти</a>
                        <a class="p-2 btn btn-outline-warning" href="{% url 'user:register' %}">Регистрация</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
    <p class="lead">{{ description }}</p>
</div>

<div class="container">
    {% block content %}
    {% endblock %}
</div>

<div class="container">
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023 - {% now 'Y' %}</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'blog:post_list' %}">Статьи</a></li>
                    <li><a class="text-muted" href="{% url 'client:client_list' %}">Клиенты</a></li>
                    <li><a class="text-muted" href="{% url 'mailer:message_list' %}">Письма</a></li>
                    <li><a class="text-muted" href="{% url 'mailer:settings_list' %}">Рассылки</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>